### ISSUE TITLE
Failing to connect landings to roads in this example

### ISSUE THREAD

**Issue by josie-hughes** [LandSciTech/roads#4]
cost=cMap;cost[cost>0]=0;cost[cMap==0]=100
    
      
    rds = raster::rasterToPoints(cMap, fun = function(x){x > 0},
                                 spatial = TRUE) 
    rds=spsample(rds,n=1,type="random")
    
    nw = roads::projectRoadsNew(landings = cMap,
                                       cost = cost,
                                       roads = rds,roadsOut="sf")

**Comment by see24** [comment]
@josie-hughes can you add the code to create cMap? And when you say failing to connect landings to roads does that mean the results have new roads but they don't go to the landings or there are no new roads created? Thanks!

**Comment by see24** [comment]
I implemented this in a function but it is still not perfect. Although it is better than the existing rasterToLineSegments. The problem is if there is a clump of raster cells at the intersection of two roads you get a messed up line since the cost is the same in all directions. 
![image](https://user-images.githubusercontent.com/39161074/128073325-63b7bdea-2b30-4344-b925-b2ab466934bf.png)

![image](https://user-images.githubusercontent.com/39161074/128073263-0dcf069e-6684-4c0d-99fb-68b34d5aa84f.png)
