### ISSUE TITLE
Given raster input and roadsOut= "sf" output road network rather than mix of points and lines.

### ISSUE THREAD

**Issue by josie-hughes** [LandSciTech/roads#5]

**Comment by see24** [comment]
Currently not able to do but if we can make a better version of rasterToLineSegments then that would fix it. The problem is there is no ordering to the points so unless it is one simple road the is no way to connect them in the right order. The points was a work around to avoid having to change road rasters to lines which took a long time. It might also be possible to resurrect the old version of the package that had a better way of handling raster roads but was slower for vector inputs.
